#!/usr/bin/env python3

import argparse
import subprocess
import re

parser = argparse.ArgumentParser()
parser.add_argument('input', help='input file (.svg)')
parser.add_argument('output', nargs='?', help='Output File (.gcode)')
parser.add_argument('-d', '--dim', help='Include draw boundaries',
    action='store_true')
args = parser.parse_args()

def change_ending(filename, repl):
    return re.sub("\.[^.]*$", repl, filename)

JUICY = "juicy-gcode-0.1.0.5"
with open(args.input) as f:
    svg = f.read()
    # remove all objects with opacity 0.99*
    clean_svg = re.sub(r"<[^>]*opacity:0.99[^>]*>\s*", "", svg, flags=re.MULTILINE | re.DOTALL)

temp_filename = change_ending(args.input, ".gcode.tmp")
with open(temp_filename, "w+") as f:
    f.write(clean_svg)

p = subprocess.run([f"{JUICY}/juicy-gcode", temp_filename,
    "-f", f"{JUICY}/config", "-d", "1"], stdout=subprocess.PIPE)

output = args.output
if output is None:
    output = change_ending(args.input, ".gcode")
    print(output);
with open(output, "wb") as f:
    f.write(p.stdout);

